### ISSUE TITLE
Adding matchers in 'bulk'

### ISSUE THREAD

**Issue by mangospace** [medspacy/target_matcher#2]
What might be best way to add Target Rules in bulk e.g. say from a python list of clinical conditions e.g. from SNOMED ?

**Comment by mangospace** [comment]
randomlist=["hemophilia1","Diabetic Dermopathy", "Major Depression"]
for x in randomlist:
    atom=f'{x}' 
    target_rules.append(TargetRule(atom,"PROBLEM"))
target_matcher.add(target_rules)

**Comment by burgersmoke** [comment]
Yes, this code should function and work.

One thing to keep in mind is that I don't believe any of us have attempted adding more than dozens or hundreds of targets at a time.  So there may be performance considerations if you need to use thousands or more.  If you do run into performance issues, please let us know, as there may be other more performant options you might need to consider.  But if you're using smaller volume, I think you will be fine.
